#!/usr/bin/env bash
# Subdomain www to point to load-balancer IP

my_bash_func()
{
if [ "$#" -eq 2 ];
then
dig $2.$1 | grep -A1 'ANSWER SECTION' | awk -v subdom=$2 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
else
dig "www".$1 | grep -A1 'ANSWER SECTION' | awk -v subdom="www" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
dig "lb-01".$1 | grep -A1 'ANSWER SECTION' | awk -v subdom="lb-01" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
dig "web-01".$1 | grep -A1 'ANSWER SECTION' | awk -v subdom="web-01" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
dig "web-02".$1 | grep -A1 'ANSWER SECTION' | awk -v subdom="web-02" 'NR==2{print "The subdomain", subdom, "is a", $4, "record and points to", $5 }'
fi
}

if [ "$#" -eq 2 ];
then
        my_bash_func "$1" "$2"
else
        my_bash_func "$1"
fi
