#!/usr/bin/env bash
#installing NGINX in the server

sudo apt update &&
sudo apt -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index file and start
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html &&
sudo /etc/init.d/nginx start
