#!/usr/bin/env bash
#installing NGINX in the server

sudo apt update &&
sudo apt -y install nginx
#Firewall
sudo ufw allow 'Nginx HTTP'
#Index file and start
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html &&
sudo /etc/init.d/nginx start
#Redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=vgiDcJi534Y permanent;' /etc/nginx/sites-available/default
#404 Page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
#Restart
sudo /etc/init.d/nginx restart
