#!/usr/bin/env bash
# script repairs nginx to conect the port 0:80
rm /etc/nginx/sites-enabled/default | ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default | service nginx restart
