#!/usr/bin/env bash
#script that displais 10 times 'Holberton Scool'
i=0
while [ $i -lt 10 ] 
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$(( i + 1 ))
    
done
